const AUGMENT_ICON_MAP = {
  "Chỉ Huy Siêu Thú": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/animacommander_ii.tft_set17.png",
  "Nữ Chiến Binh Khiên": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/missing-t1.png",
  "Nhiệt Tử": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/starconqueror_ii.tft_set17.png",
  "Zed Kẻ Xâm Lăng": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/invaderzed_ii.tft_set17.png",
  "Thần Luật Khả Biến": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/missing-t2.png",
  "Liên Hoàn Tinh Tú": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/aatroxhero_i.tft_set17.png",
  "Meep Cực Tốc": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/poppyhero_i.tft_set17.png",
  "Siêu Vũ Trụ": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/meepspace9_ii.tft_set17.png",
  "Sát Thủ Đánh Thuê": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/contractkiller_ii.tft_set17.png",
  "Vươn Tới Tinh Tú": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/reachforthestars_ii.tft_set17.png",
  "Ổ Bắn Tỉa": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/snipersnest2.png",
  "Lò Rèn Thăng Hoa": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/job_s-done-ii.png",
  "Khúc Ca Du Mục": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/shepherdssong_ii.tft_set17.png",
  "Du Hành Dải Ngân Hà": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/missing-t2.png",
  "Boong!": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/bonk_i.tft_set17.png",
  "Tự Hủy": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/selfdestruct_ii.tft_set17.png",
  "Gánh Tạ": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/liftingcompetition_ii.tft_set17.png",
  "Trái Tim Của Hiểm Họa": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/missing-t3.png",
  "U.R.F.": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/ultrarapidfire_ii.tft_set16.png",
  "Triệu Gọi Hỗn Mang": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/calltochaos_iii.png",
  "Cái Giá Phải Trả": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/atwhatcost_iii.png",
  "Rồng Đẻ Trứng Vàng": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/the-golden-egg-iii.png",
  "Báo Oán": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/retribution_iii.tft_set16.png",
  "Tối Đa Hóa": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/minmax_iii.tft_set16.png",
  "Arcane Viktor-y": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/arcaneviktory_ii.png",
  "Xúc Xắc Hoành Tráng": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/epicrolldown_ii.png",
  "Đội Hình Tối Ưu": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/maxbuild_ii.png",
  "Thanh Lý Toàn Bộ": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/firesale_i.tft_set13.png",
  "Cắm Rễ Phân Tán": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/spreadingroots_ii.tft_set16.png",
  "Khổng Lồ Hóa": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/tiny-titans-i.png",
  "Kẻ Sống Sót": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/survivor_i.tft_set13.png",
  "Túi Đồ Cỡ Nhỏ": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/smallgrabbag_i.tft_set16.png",
  "Chiến Tướng Khải Hoàn": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/unforgotten_ii.tft_set16.png",
  "Xây Dựng Đội Hình": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/building-an-army-i.png",
  "Linh Thú Vào Bếp": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/tacticianskitchen_iii.tft_set13.png",
  "Sống Vội": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/hyperroll2.png",
  "Băng Trộm II+": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/bandthieves3.png",
  "To Lớn & Mạnh Mẽ": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/giantandmighty_iii.tft_set12.png",
  "Cấy Ghép Siêu Công Nghệ": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/cybernetic2.png",
  "Nhân Bản": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/replication-ii.png",
  "Hình Nộm Va Chạm": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/crash-test-dummies-ii.png",
  "Đo Ni Đóng Giày+": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/lucky-gloves-iii.png",
  "Hình Nhân Hóa": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/dummify_i.tft_set13.png",
  "Kiên Nhẫn Là Một Đức Tính": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/patienceisavirtue_i.tft_set12.png",
  "Mũ Tử Thần": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/deadliercaps_ii.tft_set15.png",
  "Nhỏ Mà Có Võ": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/tinybutdeadly_iii.png",
  "Nâng Tầm Uy Lực": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/powerup_i.tft_set13.png",
  "Túi Đồ Urf": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/urfs-grab-bag-iii.png",
  "Hang Ổ Baron": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/thebaronslair_iii.tft_16_4.png",
  "Kết Nối Gián Đoạn": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/missed-connections-i.png",
  "Toàn Thắng": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/winout_iii.tft_set16.png",
  "Tất Tay Bậc Đồng II": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/bronzeforlife_iii.tft_set13.png",
  "Củng Cố Tuyến Trước": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/frontlinefoundation_ii.tft_set17.png",
  "Bộ Ba Hoàn Hảo I": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/trifecta-ii.png",
  "Bài Học Sơ Khai": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/earlylearning_ii.png",
  "Tiêu Dùng Thông Minh": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/wisespending3.png",
  "Sơ Đồ Tuyến Sau": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/backlineblueprint_ii.tft_set17.png",
  "Bộ Ba Hoàn Hảo II": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/trifecta-iii.png",
  "Thuế Nhận Thức": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/cognitivetax_i.tft_set17.png",
  "Cây Cung Thần Tốc": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/you-have-my-bow-ii.png",
  "Một Bùa, Hai Bùa": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/onebufftwobuff_iii.tft_set13.png",
  "Lấy Công Bù Thủ I": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/glasscannon_i.tft_set13.png",
  "Hàng Chờ Pandora": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/pandoras-bench-ii.png",
  "Giáp Tự Chế I": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/makeshift1.png",
  "Thuế Nhận Thức+": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/cognitivetax_i.tft_set17.png",
  "Giáp Tự Chế II": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/makeshift2.png",
  "Đẩy Nhanh Tiến Độ": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/upwardmobility_iii.tft_set12.png",
  "Tăng Trưởng Bùng Nổ+": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/explosivegrowth_ii.tft_set12.png",
  "Tăng Trưởng Bùng Nổ": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/explosivegrowth_ii.tft_set12.png",
  "Bạn Thân II": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/best-friends-ii.png",
  "Bừa Bộn": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/dizzy-ii.png",
  "Bạn Thân I": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/best-friends-i.png",
  "Vương Miện Nặng Trĩu": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/heavyisthecrown_ii.tft_set15.png",
  "Chỉ Một Con Đường": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/hardcommit_iii.tft_set12.png",
  "Trượng Đại Thiên Sứ": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/seraphimsstaff_ii.tft_set16.png",
  "Ôm Tập Thể II": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/grouphug2_ii.tft_set17.png",
  "Kho Báu Chôn Giấu": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/buried-treasures-iii.png",
  "Ôm Tập Thể I": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/grouphug1_i.tft_set17.png",
  "Ma Thuật Đan Kết": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/wovenmagic_iii.tft_set16.png",
  "Cuộc Viễn Chinh": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/expedition_i.tft_set17.png",
  "Cầu Hồi Phục I": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/healing-orbs-i.png",
  "Cây Tộc Hệ+": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/thetraittree_iii.tft_set16.png",
  "Leo Hạng II": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/climbtheladder_ii.tft_set13.png",
  "Leo Hạng I": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/climbtheladder_i.tft_set13.png",
  "Đo Ni Đóng Giày": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/lucky-gloves-iii.png",
  "Lập Đội": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/teaming-up-i.png",
  "Thép Mạ Vàng": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/gildedsteel_ii.tft_16_4.png",
  "Tụ Điện II": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/electrocharge-ii.png",
  "Tiền Ăn Trưa": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/bloodbank_i.png",
  "Tụ Điện I": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/electrocharge-i.png",
  "Chờ Đợi Xứng Đáng": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/worththewait_ii.tft_set12.png",
  "Phân Nhánh+": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/branching-out-i.png",
  "Tiếp Tế Trang Bị": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/itemgrabbag1.png",
  "Thích Mở Rộng": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/going-long-iii.png",
  "Thợ Rèn Gậy": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/rodsmith_ii.tft_set16.png",
  "Kỳ Vọng Bất Ngờ": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/addicted-to-rolling-iii.png",
  "Giữ Vững Hàng Ngũ": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/holdtheline_iii.tft_set15.png",
  "Phóng Hỏa": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/sunfireboard2.png",
  "Kho Báu Sắt": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/iron-assets-i.png",
  "Nếm Mùi Lửa": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/feedtheflames_ii.tft_set16.png",
  "Quỹ Phòng Hộ+": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/richgetricher3.png",
  "Ván Cược Hoàng Kim": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/goldengamble_iii.tft_set17.png",
  "AFK": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/afk-i.png",
  "Quỹ Phòng Hộ": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/richgetricher3.png",
  "2 Vàng Là Nhất": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/twomuchvalue_ii.tft_set13.png",
  "Túi Đồ Siêu Hùng+": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/heroic-grab-bag-ii.png",
  "Cung Dự Phòng": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/recurvewrecker_i.tft_set16.png",
  "Hào Quang Nhân Vật Chính": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/plotarmor_ii.tft_set15.png",
  "Trái Tim Sắt Đá": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/healthygains_ii.tft_set16.png",
  "Chuyển Đổi Năng Lượng I": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/chargetransfer1_i.tft_set17.png",
  "Túi Đồ Siêu Hùng++": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/heroic-grab-bag-ii.png",
  "Nhà Máy Tái Chế": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/salvage2.png",
  "Chuyển Đổi Năng Lượng II": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/chargetransfer2_ii.tft_set17.png",
  "Kiên Nhẫn Học Tập": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/learning-from-experience-ii.png",
  "Ván Cược URF": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/urfsgambit_ii.tft_set16.png",
  "Hạ Đo Ván": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/slammin_ii.png",
  "Tất Tay Bậc Đồng I": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/bronzeforlife_ii.tft_set13.png",
  "Tái Lập Vũ Trụ": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/cosmicrestart_ii.tft_set17.png",
  "Sét Cao Thế": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/highvoltage_ii.tft_set12.png",
  "Tôi Thăng Cấp Một Mình": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/sololeveling_ii.tft_set15.png",
  "Độc Hành I": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/exiles1.png",
  "Săn Kho Báu": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/treasurehunt_ii.tft_set15.png",
  "Quay Trúng Thưởng": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/slightlymagicroll_i.tft_set16.png",
  "Tiền Vệ Trung Tâm": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/findyourcenter_i.tft_set12.png",
  "Được Này Mất Kia I": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/good-for-something-i.png",
  "Nhà Máy Tái Chế+": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/salvage2.png",
  "Linh Hồn Chuộc Tội": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/spiritofredemption_ii.tft_set16.png",
  "Song Sát Tốc Hành": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/speedydoublekill_ii.png",
  "Nghĩ Về Tương Lai": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/forwardthinking_ii.tft_set13.png",
  "Hút Sinh Lực I": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/dhampyr_ii.tft_set13.png",
  "Hút Sinh Lực II": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/dhampyr_ii.tft_set13.png",
  "Linh Hoạt": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/flexible_ii.tft_set12.png",
  "Tái Khởi Động Nhiệm Vụ": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/restartmission_i.tft_set12.png",
  "Hàng Chờ Đấu Đôi": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/duoqueue_ii.tft_set12.png",
  "Hạ Đo Ván+": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/slammin_ii.png",
  "Khuyến Mãi Kinh Nghiệm": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/levelup3.png",
  "Sức Sống Mới II": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/second--wind-ii.png",
  "Song Vệ": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/twinguardians_i.tft_set16.png",
  "Ngọn Gió Thứ Hai": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/second--wind-i.png",
  "Ván Cược Hoàng Kim+": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/goldengamble_iii.tft_set17.png",
  "Cuộc Phiêu Lưu Tôn Quý": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/exaltedadventure_iii.tft_set13.png",
  "Nhất Thống": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/standunited1.png",
  "Cảm Thấy May Mắn": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/feelinglucky_i.tft_set17.png",
  "Vay Tạm Ứng": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/advancedloan_ii.tft_set16.png",
  "Kim Long": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/thegoldendragon_ii.png",
  "Triệu Hồi Bất Tận": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/hyperbolicrodextender_i.tft_set16.png",
  "Một, Hai, Năm!": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/one-two-five-i.png",
  "Đặc Quyền Phú Gia": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/silver-spoon-i.png",
  "Bảo Hộ Vô Tận": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/infinityprotection_ii.png",
  "Chế Tạo Bằng Hữu": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/constructacompanion_iii.tft_set16.png",
  "Gói Bảo Hộ": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/carepackage_ii.tft_set15.png",
  "Thợ Rèn Kiếm": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/swordsmith_ii.tft_set16.png",
  "Kỷ Nguyên+": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/epoch_ii.png",
  "Kamekameha": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/furiousblows_ii.tft_set16.png",
  "Phi Vụ Trang Bị": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/museumheist_iii.tft_set16.png",
  "Aura Farming": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/aurafarming_ii.tft_set15.png",
  "Đam Mê Đai Lưng": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/beltoverflow_iii.tft_set13.png",
  "Tôi Luyện Sức Mạnh": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/forgedinstrength_iii.png",
  "Một Hai Ba": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/threes-company-i.png",
  "Cây Tộc Hệ": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/thetraittree_iii.tft_set16.png",
  "Tài Khoản Tiết Kiệm": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/savingsaccount_ii.tft_set16.png",
  "Khéo Tay Hay Làm": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/craftedcrafting_i.tft_set13.png",
  "Khảm Bảo Thạch I": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/jeweled-lotus-ii.png",
  "Sinh Nhật Đoàn Tụ": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/birthdayreunion_ii.png",
  "Vương Miện Hắc Hóa": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/cursedcrown-iii.png",
  "Lựa Chọn Độc Quyền II": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/exclusivecustomization_ii.tft_set15.png",
  "Võ Sĩ Giác Đấu": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/prizefighter_ii.png",
  "Túi Đồ Siêu Hùng": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/heroic-grab-bag-ii.png",
  "Lựa Chọn Độc Quyền": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/exclusivecustomization_ii.tft_set15.png",
  "Đầu Tư++": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/invested-iii.png",
  "Đam Mê Gậy": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/wandoverflow_iii.tft_set13.png",
  "Quang Lân Tiểu Yêu": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/roll-the-dice-iii.png",
  "Cắm Rễ Phân Tán+": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/spreadingroots_ii.tft_set16.png",
  "Thăng Hoa": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/ascension2.png",
  "Tiền Tuyến Vững Chãi": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/lineup-i.png",
  "Trang Bị Pandora II": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/pandora2.png",
  "Gói Đăng Ký Hạng Sang": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/luxurysubscription_iii.tft_set16.png",
  "Gói Tăng Cường": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/boosterpack1_ii.tft_set17.png",
  "Ván Cược Hoàng Kim++": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/goldengamble_iii.tft_set17.png",
  "Lấy Công Bù Thủ II": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/glasscannon_ii.tft_set13.png",
  "Xoay Bài Tự Động": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/recombobulator-i.png",
  "Những Người Bạn Nhỏ": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/little-buddies-ii.png",
  "Giáp Gai Thép": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/thornplatedarmor_ii.tft_set12.png",
  "Vay Tạm Ứng+": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/advancedloan_ii.tft_set16.png",
  "Trung Tâm Thương Mại": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/trade3.png",
  "Tập Trung Hỏa Lực": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/marksman_i.tft_set16.png",
  "Phản Ứng Phụ": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/sideeffects_ii.tft_set17.png",
  "Đầu Tư+": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/invested-iii.png",
  "Huấn Luyện Cận Vệ": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/bodyguardstraining_ii.png",
  "Giọt Lệ Bi Ai": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/crymeariver_ii.tft_set15.png",
  "Xúc Xắc Ma Pháp": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/a-magical-roll-ii.png",
  "Đam Mê Kiếm": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/bladeoverflow_iii.tft_set13.png",
  "Tòa Tháp": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/thetower_i.tft_set17.png",
  "Kề Vai Sát Cánh": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/westicktogether_iii.png",
  "Thông Thoáng": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/clearmind2.png",
  "Chờ Đợi Xứng Đáng II": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/worththewait_iii.tft_set12.png",
  "Lệch Chuẩn": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/misfits_ii.tft_set17.png",
  "Xúc Xắc Vô Tận I": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/rolling-for-days-i.png",
  "Động Cơ Tăng Tốc": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/clockworkaccelerator_ii.tft_set12.png",
  "Băng Trộm II": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/bandthieves3.png",
  "Tự Lập Đội": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/constructacompanion_iii.tft_set16.png",
  "Cặp Đôi Siêu Cứng": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/two-tanky-ii.png",
  "Ăn Mòn": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/corrosion_i.tft_set13.png",
  "Tập Chịu Đòn": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/boxinglessons_i.tft_set16.png",
  "Hướng Đến Hồi Kết": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/late-game-specialist-i.png",
  "Quà Sinh Nhật": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/golden-gifts-iii.png",
  "Sát Thủ Khát Máu": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/indiscriminateslayer_ii.tft_set16.png",
  "Tinh Túy Kim Long": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/shimmerscaleessence_iii.tft_set12.png",
  "Lệ Lưu Ly": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/griefofthegreatgoddess_i.tft_set16.png",
  "Phân Nhánh": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/branching-out-i.png",
  "Khiên Đơn Đấu": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/soloplate_ii.tft_set16.png",
  "Món Quà Ngọt Ngào": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/sweettreats_iii.png",
  "Dịch Vụ Gói Đăng Ký": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/subscriptionservice_iii.tft_set12.png",
  "Độc Hành II": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/exiles2.png",
  "Băng Trộm II++": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/bandthieves3.png",
  "Tứ Phương Tiếp Viện": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/reinfourcement_ii.png",
  "NHẮM MẮT CHƠI BỪA": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/noscoutnopivot_ii.tft_set13.png",
  "Thăng Tiến Cuối Trận": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/lategamescaling_ii.tft_set16.png",
  "Cơn Khát Vàng": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/moneyhungry1_ii.tft_set17.png",
  "Trên Đà Phát Triển": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/onaroll_i.tft_set16.png",
  "Dòng Tiền Mờ Ám": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/mirroredmonetization_ii.tft_set13.png",
  "Trang Bị Pandora III": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/pandora3.png",
  "Số 4 Hoàn Hảo": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/maythefoursbewithyou_ii.tft_set17.png",
  "Khu Giao Dịch": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/trade2.png",
  "Ăn Trộm": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/pilfer_ii.tft_set12.png",
  "Túi Đồ Cỡ Đại": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/grab-bag-ii.png",
  "Bước Đột Phá": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/criticalsuccess_i.tft_set16.png",
  "Vé Kim Cương": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/goldenticket3.png",
  "Mở Lối": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/carveapath_i.tft_set16.png",
  "Đồng Minh Của Bụt": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/caretaker_s-chosen-i.png",
  "Người Bạn Vàng": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/constructacompanion_iii.tft_set16.png",
  "Thua Có Tính Toán": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/calculatedloss2.png",
  "Nước Đi Liều Lĩnh": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/risky-moves-i.png",
  "Tuyển Nhân Sự": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/newrecruit3.png",
  "Thức Tỉnh Linh Hồn": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/awakenedsoul_iii.tft_set16.png",
  "Băng Trộm": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/bandthieves1.png",
  "Chuyện Đời Thường": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/slice_of_life_i.tft_set15.png",
  "Khảm Bảo Thạch II": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/jeweled-lotus-iii.png",
  "Bão Vàng": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/moneymonsoon_iii.tft_set16.png",
  "Chế Tạo Tại Chỗ": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/living-forge-iii.png",
  "Đường Ra Trận": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/warpath_ii.tft_set13.png",
  "Huyết Tế": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/trailofblood_ii.tft_set16.png",
  "Khóa Dự Phòng": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/extrabuckles_i.tft_set16.png",
  "Ý Chỉ Xích Chùy": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/will-of-the-flail-ii.png",
  "Quân Đoàn 3 Sao": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/legionofthrees_ii.png",
  "Kích Cỡ Là Quan Trọng": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/sizematters_i.tft_set17.png",
  "Cộng Mệt Nghỉ!": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/tons-of-stats-ii.png",
  "Gói Tăng Cường++": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/choiceui/boosterpack1_ii.tft_set17.png",
  "Khổng Lồ Tí Hon": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/tiniest-titaniii.png",
  "Gói Tăng Cường+": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/boosterpack1_ii.tft_set17.png",
  "Bán Thăng Hoa": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/ascension1.png",
  "Kỷ Nguyên": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/epoch_ii.png",
  "Cầu Hồi Phục II": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/healing-orbs-ii.png",
  "Hộp Pandora": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/pandora1.png",
  "Lò Rèn Thần Thoại": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/portableforge2.png",
  "Quá Tải Tư Duy": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/cognitiveoverload_ii.tft_set17.png",
  "Khởi Động Nhanh": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/kickstart_i.tft_set17.png",
  "Lò Rèn Tiềm Ẩn": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/long-time-crafting-i.png",
  "Cố Gắng Lật Kèo": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/comebackstory_iii.tft_set16.png",
  "Trí Tuệ Siêu Công Nghệ": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/cybernetic-uplink-ii.png",
  "Kiếm Tử Thần": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/deadlierblades_ii.tft_set15.png",
  "Tín Đồ Mua Sắm": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/silver-ticket-iii.png",
  "Đánh Là Trúng": "https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/justhit_iii.tft_set16.png"
};
